cmake_minimum_required(VERSION 3.31)
set(CMAKE_PROJECT_TOP_LEVEL_INCLUDES .devcontainer/cmake/xproinc.cmake)
project(wxTetris VERSION 1.1.0)
include(xptoplevel)
set(exe_srcs src/App.cpp src/Tetris.cpp src/Tetris.hpp LICENSE)
add_executable(${PROJECT_NAME} WIN32 ${exe_srcs})
find_package(wxwidgets)
target_link_libraries(${PROJECT_NAME} PRIVATE wx::core)
include(GNUInstallDirs)
set(XP_INSTALL_CMAKEDIR ${CMAKE_INSTALL_DATADIR}/cmake)
set(targetsFile ${PROJECT_NAME}-targets)
xpPackageDevel(TARGETS_FILE ${targetsFile} EXE ${PROJECT_NAME})
install(TARGETS ${PROJECT_NAME} EXPORT ${targetsFile})
install(EXPORT ${targetsFile} DESTINATION ${XP_INSTALL_CMAKEDIR})
xpSourceListAppend("${exe_srcs}")
