cmake_minimum_required(VERSION 3.31)
set(CMAKE_PROJECT_TOP_LEVEL_INCLUDES .devcontainer/cmake/xproinc.cmake)
project(wxTetris VERSION 1.0.0)
include(xptoplevel)
set(exe_srcs src/App.cpp src/Tetris.cpp src/Tetris.hpp LICENSE)
add_executable(${PROJECT_NAME} WIN32 ${exe_srcs})
find_package(wxwidgets)
target_link_libraries(${PROJECT_NAME} PRIVATE wx::core)
install(TARGETS ${PROJECT_NAME})
set(CPACK_GENERATOR TXZ)
xpGetVersionString(CPACK_PACKAGE_VERSION)
if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64|ARM64)$")
  set(CPACK_SYSTEM_NAME "${CMAKE_SYSTEM_NAME}-arm64")
endif()
include(CPack)
xpSourceListAppend("${exe_srcs}")
